### ISSUE TITLE
NetworkingV1Api object has no attribute read_ingress

### ISSUE THREAD

**Issue by sepich** [2gis/k8s-handle#141]
K8s v1.22 has dropped support for Ingress resource in `networking.k8s.io/v1beta1` and only `networking.k8s.io/v1` is supported. Unfortunately k8s-handler fails like:
```
$ cat templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80

$ k8s-handle diff --section test
...
Traceback (most recent call last):
  File "/Users/alexander.ryabov/Projects/k8s-handle/venv/bin/k8s-handle", line 7, in <module>
    k8s_handle.main()
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/__init__.py", line 239, in main
    args.func(args_dict)
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/__init__.py", line 53, in handler_diff
    _handler_deploy_destroy(args, COMMAND_DIFF)
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/__init__.py", line 67, in _handler_deploy_destroy
    _handler_provision(
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/__init__.py", line 128, in _handler_provision
    executor.run(resource)
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/k8s/diff.py", line 71, in run
    k8s_object = kube_client.get()
  File "/Users/alexander.ryabov/Projects/k8s-handle/k8s_handle/k8s/adapters.py", line 88, in get
    response = getattr(self.api, 'read_{}'.format(self.kind))(self.name)
AttributeError: 'NetworkingV1Api' object has no attribute 'read_ingress'
```
Ok, i see legacy kubernetes-client:
https://github.com/2gis/k8s-handle/blob/b484e469392d42e7f57642184249729d0ab99e82/requirements.txt#L4
and thought i can fix it via bumping to latest 18.20.0. But it is not available there too:
https://github.com/kubernetes-client/python/issues?q=is%3Aissue+is%3Aopen+ingress
Actually kubernetes-client looks abandoned. 

So, for now it seems the fix is to skip Ingress availability checking and just apply it as raw object:
```diff
$ git diff
diff --git a/k8s_handle/k8s/adapters.py b/k8s_handle/k8s/adapters.py
index f09442a..731e5a4 100644
--- a/k8s_handle/k8s/adapters.py
+++ b/k8s_handle/k8s/adapters.py
@@ -18,7 +18,6 @@ RE_CREATE_TIMEOUT = 1

 class Adapter:
     api_versions = {
-        'apps/v1beta1': client.AppsV1beta1Api,
         'v1': client.CoreV1Api,
         'extensions/v1beta1': client.ExtensionsV1beta1Api,
         'batch/v1': client.BatchV1Api,
@@ -40,7 +39,7 @@ class Adapter:
     }
     kinds_builtin = [
         'ConfigMap', 'CronJob', 'DaemonSet', 'Deployment', 'Endpoints',
-        'Ingress', 'Job', 'Namespace', 'PodDisruptionBudget', 'ResourceQuota',
+        'Job', 'Namespace', 'PodDisruptionBudget', 'ResourceQuota',
         'Secret', 'Service', 'ServiceAccount', 'StatefulSet', 'StorageClass',
         'PersistentVolume', 'PersistentVolumeClaim', 'HorizontalPodAutoscaler',
         'Role', 'RoleBinding', 'ClusterRole', 'ClusterRoleBinding', 'CustomResourceDefinition',
diff --git a/requirements.txt b/requirements.txt
index 8388329..0ba5a54 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 requests==2.25.0
 jinja2==2.11.3
-PyYAML==5.4
-kubernetes==12.0.1
+PyYAML==5.4.1
+kubernetes==18.20.0
 semver==2.13.0
```
I can submit MR if the fix looks fine for you (`apps/v1beta1` has been dropped in k8s 1.16)

**Comment by rvadim** [comment]
AFAIK k8s-handle does't special process for an Ingress updated. So, patch is sutable.

**Comment by sepich** [comment]
I've verified that it is fixed by https://github.com/2gis/k8s-handle/pull/142
