### ISSUE TITLE
Update of PodDisruptionBudget cause exception

### ISSUE THREAD

**Issue by dekhtyarev** [2gis/k8s-handle#17]
First deploy works ok:
```
$ k8s-handle deploy --section staging-pdb
2018-08-24 02:07:16 INFO:__main__:Using default namespace test
2018-08-24 02:07:16 INFO:templating:Trying to generate file from template "poddisruptionbudget.yaml.j2" in "/tmp/k8s-handle"
2018-08-24 02:07:16 INFO:templating:File "/tmp/k8s-handle/poddisruptionbudget.yaml" successfully generated
2018-08-24 02:07:16 INFO:k8s.resource:PodDisruptionBudget "k8s-starter-kit-dekhtyarev" does not exist, create it
2018-08-24 02:07:16 ERROR:k8s.resource:Invalid value for `disrupted_pods`, must not be `None`
```
Redeploy without changes cause exception:
```
$ k8s-handle deploy --section staging-pdb
2018-08-24 02:10:08 INFO:__main__:Using default namespace test
2018-08-24 02:10:08 INFO:templating:Trying to generate file from template "poddisruptionbudget.yaml.j2" in "/tmp/k8s-handle"
2018-08-24 02:10:08 INFO:templating:File "/tmp/k8s-handle/poddisruptionbudget.yaml" successfully generated
Traceback (most recent call last):
  File "/opt/k8s-handle/k8s-handle", line 117, in <module>
    main()
  File "/opt/k8s-handle/k8s-handle", line 90, in main
    p.run(resource)
  File "/opt/k8s-handle/k8s/resource.py", line 156, in run
    self._deploy(file_path)
  File "/opt/k8s-handle/k8s/resource.py", line 195, in _deploy
    if kube_client.get() is None:
  File "/opt/k8s-handle/k8s/resource.py", line 403, in get
    self.name, namespace=self.namespace)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/policy_v1beta1_api.py", line 1574, in read_namespaced_pod_disruption_budget
    (data) = self.read_namespaced_pod_disruption_budget_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/policy_v1beta1_api.py", line 1665, in read_namespaced_pod_disruption_budget_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1beta1_pod_disruption_budget_status.py", line 66, in __init__
    self.disrupted_pods = disrupted_pods
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1beta1_pod_disruption_budget_status.py", line 143, in disrupted_pods
    raise ValueError("Invalid value for `disrupted_pods`, must not be `None`")
ValueError: Invalid value for `disrupted_pods`, must not be `None`
ERROR: Job failed: exit code 1
```

yaml of PodDisruptionBudget:
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: 2018-08-24T02:07:16Z
  generation: 1
  name: test-k8s-handle
  namespace: test
  resourceVersion: "257484967"
  selfLink: /apis/policy/v1beta1/namespaces/test/poddisruptionbudgets/test-k8s-handle
  uid: 6ca7f4ac-a742-11e8-bee7-fa163e24fbac
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: test-k8s-handle
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptedPods: null
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
```

**Comment by dekhtyarev** [comment]
Released by https://github.com/2gis/k8s-handle/releases/tag/0.6.0
